export interface TreatedCluster {
  DEM360: string;
  cluster_no: string;
  'Treatment Name': string;
  treatmentid: string;
  center_lng: number;
  Lon: number;
  center_lat: number;
  Lat: number;
  Stem6to9_tonsAcre: number;
  stem6to9_tonsacre: number;
  Stem4to6_tonsAcre: number;
  stem4to6_tonsacre: number;
  Stem9Plus_tonsAcre: number;
  stem9Plus_tonsacre: number;
  Branch_tonsAcre: number;
  branch_tonsacre: number;
  Foliage_tonsAcre: number;
  foliage_tonsacre: number;
  Forest_type: string;
  forest_type: string;
  County: string;
  county_name: string;
  Hazard_Class: number;
  haz_class: number;
  Land_Ownership: string;
  land_use: string; 
  site_class: string;
  center_elevation: number;
  slope: number;
  area: number;
  landing_lng: number;
  landing_lat: number;
  landing_elevation: number;  
  mean_yarding: number;
  year: number;
  wood_density: number;
}
